name: precompile

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: "prod"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.x
          elixir-version: 1.14.x
      - name: Install Dependencies
        run: |
          sudo apt-get update
          # we don't need g++ compiler but we `cc_precompiler` looks for
          # g++ executable to detect the target
          sudo apt-get install -y gcc make curl tar \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

          # install x86_64 musl cross-compiler
          TARGET=x86_64-linux-musl-cross
          curl -s https://more.musl.cc/11.2.1/x86_64-linux-musl/$TARGET.tgz | tar -xz
          echo "$PWD/$TARGET/bin" >> $GITHUB_PATH

          # install aarch64 musl cross-compiler
          TARGET=aarch64-linux-musl-cross
          curl -s https://more.musl.cc/11.2.1/x86_64-linux-musl/$TARGET.tgz | tar -xz
          echo "$PWD/$TARGET/bin" >> $GITHUB_PATH
      - run: |
          mix deps.get
          MIX_ENV=test mix test
      - name: Pre-compile NIF library
        run: |
          export ELIXIR_MAKE_CACHE_DIR=$(pwd)/cache
          mkdir -p "${ELIXIR_MAKE_CACHE_DIR}"
          mix elixir_make.precompile
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cache/*.tar.gz

  macos:
    runs-on: macos-11
    env:
      MIX_ENV: "prod"
    steps:
      - uses: actions/checkout@v3
      - name: Install Erlang & Elixir
        run: |
          brew install erlang elixir
          mix local.hex --force
          mix local.rebar --force
      - run: |
          mix deps.get
          MIX_ENV=test mix test
      - name: Pre-compile NIF library
        run: |
          export ELIXIR_MAKE_CACHE_DIR=$(pwd)/cache
          mkdir -p "${ELIXIR_MAKE_CACHE_DIR}"
          mix elixir_make.precompile
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cache/*.tar.gz
