name: precompile

on:
  - push

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: "prod"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.x
          elixir-version: 1.14.x
      - name: Cache musl cross compilers
        id: cache-musl
        uses: actions/cache@v3
        env:
          cache-name: cache-musl
        with:
          path: |
            x86_64-linux-musl-cross
            aarch64-linux-musl-cross
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - if: ${{ steps.cache-musl.outputs.cache-hit != 'true' }}
        name: Setup musl compilers
        continue-on-error: true
        run: |
          curl -s https://more.musl.cc/11.2.1/x86_64-linux-musl/x86_64-linux-musl-cross.tgz | tar -xz
          curl -s https://more.musl.cc/11.2.1/x86_64-linux-musl/aarch64-linux-musl-cross.tgz | tar -xz
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make curl tar \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf
          echo "$PWD/x86_64-linux-musl-cross/bin" >> $GITHUB_PATH
          echo "$PWD/aarch64-linux-musl-cross/bin" >> $GITHUB_PATH
      - run: |
          mix deps.get
          MIX_ENV=test mix test
      - name: Pre-compile NIF library
        run: |
          export ELIXIR_MAKE_CACHE_DIR=$(pwd)/cache
          mkdir -p "${ELIXIR_MAKE_CACHE_DIR}"
          mix elixir_make.precompile
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cache/*.tar.gz

  macos:
    runs-on: macos-11
    env:
      MIX_ENV: "prod"
    steps:
      - uses: actions/checkout@v3
      - name: Install Erlang & Elixir
        run: |
          brew install erlang elixir
          mix local.hex --force
          mix local.rebar --force
      - run: |
          mix deps.get
          MIX_ENV=test mix test
      - name: Pre-compile NIF library
        run: |
          export ELIXIR_MAKE_CACHE_DIR=$(pwd)/cache
          mkdir -p "${ELIXIR_MAKE_CACHE_DIR}"
          mix elixir_make.precompile
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cache/*.tar.gz
